### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by blackdackota** [aryanchopra/CleanMyPlaylist#1]
When I login to my account an error page pops up that with the text: "Internal Server Error," instead of taking me to the "Your playlists" part of the website.

**Comment by aryanchopra** [comment]
The app is currently going through a quota extension for it to be usable by the public. I think that's the reason for it to show the ISE, it works well with my own Spotify account which is connected to the dev console

**Comment by aryanchopra** [comment]
The app has now been granted quota extension by Spotify and is available to use for all. 🥳
